/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daz (https://sketchfab.com/Darren.Hogan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1930s-movie-camera-9310aa5cc17043949589a4eee7d08164
Title: 1930's Movie Camera
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Camera(props) {
  const { nodes, materials } = useGLTF("/assets/models/1930s_movie_camera.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group position={[-3.258, 7.216, -5.121]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera_Metal_0.geometry}
              material={materials.Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera_Metal_0_1.geometry}
              material={materials.Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera_BlackPlastic_0.geometry}
              material={materials.BlackPlastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera_Misc_0.geometry}
              material={materials.Misc}
            />
          </group>
          <group position={[-5.159, -6.357, 0.986]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyepiece_BlackPlastic_0.geometry}
              material={materials.BlackPlastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyepiece_Metal_0.geometry}
              material={materials.Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyepiece_Misc_0.geometry}
              material={materials.Misc}
            />
          </group>
          <group position={[-26.18, 1.852, 31.888]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Handle_Metal_0.geometry}
              material={materials.Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Handle_BlackPlastic_0.geometry}
              material={materials.BlackPlastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Handle_Misc_0.geometry}
              material={materials.Misc}
            />
          </group>
          <group position={[18.732, 8.216, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lenses_Misc_0.geometry}
              material={materials.Misc}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lenses_Metal_0.geometry}
              material={materials.Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lenses_BlackPlastic_0.geometry}
              material={materials.BlackPlastic}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/1930s_movie_camera.glb");
